{{- if not .Values.existingSecretsName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stoatchat.secretName" . }}
  labels:
    {{- include "stoatchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  REVOLT__PUSHD__VAPID__PRIVATE_KEY: {{ .Values.secrets.REVOLT__PUSHD__VAPID__PRIVATE_KEY | quote }}
  REVOLT__PUSHD__VAPID__PUBLIC_KEY: {{ .Values.secrets.REVOLT__PUSHD__VAPID__PUBLIC_KEY | quote }}
  REVOLT__FILES__ENCRYPTION_KEY: {{ .Values.secrets.REVOLT__FILES__ENCRYPTION_KEY | quote }}
  REVOLT__API__LIVEKIT__NODES__WORLDWIDE__KEY: {{ .Values.secrets.REVOLT__API__LIVEKIT__NODES__WORLDWIDE__KEY | quote }}
  REVOLT__API__LIVEKIT__NODES__WORLDWIDE__SECRET: {{ .Values.secrets.REVOLT__API__LIVEKIT__NODES__WORLDWIDE__SECRET | quote }}
{{- end }}
