apiVersion: v2
name: stoatchat
description: Custom Helm chart for deploying Stoatchat self-hosted services
type: application
version: 0.3.3
appVersion: "0.13.6"
keywords:
  - stoatchat
  - revolt
  - chat
  - messaging
maintainers:
  - name: Miggi
    email: noreply@mymiggi.de

dependencies:
  - name: mongodb
    version: "19.0.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: infrastructure.mongodb.enabled
  - name: valkey
    version: "2.2.5"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: infrastructure.redis.enabled
  - name: rabbitmq
    version: "2.3.0"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: infrastructure.rabbitmq.enabled
  - name: rustfs
    version: "0.3.0"
    repository: "https://rustfs.github.io/helm"
    condition: infrastructure.rustfs.enabled
